# build-all by default
default: build-all

# show this information
help:
    @just --list

# setup build env
setup:
    meson setup --reconfigure build

# build all
build-all:
    meson compile -C build

# build a specific target
build TARGET:
    meson compile -C build {{TARGET}}

# test all
test-all:
    meson test -C build

# run a specific test
test TEST:
    meson test -C build {{TEST}} --verbose

# run pre-commit
pre-commit:
    pre-commit run -a

# install(dry-run)
dry-run:
    meson install -C build --no-rebuild --only-changed --dry-run

# install library
install:
    meson install -C build --no-rebuild --only-changed

# benchmark server
bm_server:
    ./build/benchmark/benchmark_mt 4

# benchmark client
bm_client:
    wrk -t4 -c100 -d10s --latency http://127.0.0.1:8000
